Replace cURLs with on-the-wire examples
arndt-s/ietf-identity-chaining pull request #53
Opened 2023-09-22 08:02 UTC by arndt-s

Replaces examples and add response examples

2023-10-03 17:21 UTC, bc-pi requested changes
just some formatting nits in the examples

2023-10-03 17:21 UTC, bc-pi commented on identity-chaining-draft.md
> + &subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token
probably shouldn't have that leading space in HTTP examples 
```suggestion
POST /auth/token HTTP/1.1
Host: as.a.org
Content-Type: application/x-www-form-urlencoded

grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange
&resource=https%3A%2F%2Fas.b.org%2Fauth
&subject_token=ey...
&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token
```

2023-10-03 17:21 UTC, bc-pi commented on identity-chaining-draft.md
> + &assertion=ey...
```suggestion
POST /auth/token HTTP/1.1
Host: as.b.org
Content-Type: application/x-www-form-urlencoded

grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer
&assertion=ey...
```

2023-10-17 09:57 UTC, PieterKas approved these changes

2023-10-17 09:59 UTC, merged